# Generated by Django 4.1.6 on 2023-02-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('degree', models.CharField(max_length=100)),
                ('special', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
